// This file is auto-generated by Supabase CLI.
// Run: npm run db:types
// Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id:         string
          email:      string
          name:       string
          avatar_url: string | null
          plan:       string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      projects: {
        Row: {
          id:          string
          owner_id:    string
          name:        string
          description: string
          color:       string
          settings:    Json
          created_at:  string
          updated_at:  string
        }
        Insert: Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['projects']['Insert']>
      }
      macro_nodes: {
        Row: {
          id:             string
          project_id:     string
          type:           'ds' | 'journey'
          name:           string
          description:    string
          tags:           string[]
          position_x:     number
          position_y:     number
          status:         string | null
          figma_file_key: string | null
          figma_file_url: string | null
          created_at:     string
        }
        Insert: Omit<Database['public']['Tables']['macro_nodes']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['macro_nodes']['Insert']>
      }
      flows: {
        Row: {
          id:         string
          journey_id: string
          project_id: string
          name:       string
          order:      number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['flows']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['flows']['Insert']>
      }
      screens: {
        Row: {
          id:         string
          flow_id:    string
          project_id: string
          name:       string
          position_x: number
          position_y: number
          order:      number
          is_entry:   boolean
          is_error:   boolean
          status:     string
          context:    Json
          figma:      Json | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['screens']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['screens']['Insert']>
      }
      connections: {
        Row: {
          id:         string
          project_id: string
          from_id:    string
          to_id:      string
        }
        Insert: Omit<Database['public']['Tables']['connections']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['connections']['Insert']>
      }
      generation_runs: {
        Row: {
          id:            string
          project_id:    string
          journey_id:    string | null
          flow_id:       string | null
          screen_ids:    string[]
          status:        string
          model:         string
          files:         Json
          prompt_tokens: number | null
          output_tokens: number | null
          error_message: string | null
          created_at:    string
          completed_at:  string | null
        }
        Insert: Omit<Database['public']['Tables']['generation_runs']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['generation_runs']['Insert']>
      }
    }
  }
}
